# Generated by Django 3.0.3 on 2020-05-04 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GAAState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pal',
            name='numberOfRemaining',
        ),
        migrations.CreateModel(
            name='PALInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfRemaining', models.IntegerField()),
                ('price', models.IntegerField()),
                ('updateDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('PAL', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trading.PAL')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('orderDatetime', models.DateTimeField(default=datetime.datetime.now)),
                ('isFinish', models.BooleanField(default=False)),
                ('dealDateTimw', models.DateTimeField(blank=True, default=None)),
                ('GAA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.GAA')),
                ('dealWith', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='trading.PALInfo')),
            ],
        ),
        migrations.AddField(
            model_name='gaa',
            name='preference',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='trading.PAL'),
        ),
        migrations.AddField(
            model_name='gaa',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.GAAState'),
        ),
    ]
