# Generated by Django 3.0.3 on 2020-05-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaa',
            name='password',
        ),
    ]
