# Generated by Django 3.0.3 on 2020-05-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_gaa_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pal',
            name='password',
        ),
    ]
