# Generated by Django 3.0.3 on 2020-05-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20200504_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaa',
            name='preference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.PAL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dealWith',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.PALInfo'),
        ),
    ]
