# Generated by Django 3.0.3 on 2020-05-26 03:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20200521_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='PALHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updateDateTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='pal',
            name='numberOfRemaining',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='dealWith',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.PAL'),
        ),
        migrations.DeleteModel(
            name='PALInfo',
        ),
        migrations.AddField(
            model_name='palhistory',
            name='PAL',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trading.PAL'),
        ),
    ]
