# Generated by Django 3.0.3 on 2020-05-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_auto_20200526_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dealDateTimw',
            new_name='dealDateTime',
        ),
    ]
