# Generated by Django 3.0.3 on 2020-05-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_auto_20200526_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dealWith',
            new_name='PAL',
        ),
    ]
