# Generated by Django 3.0.3 on 2020-06-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20200601_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaa',
            old_name='state',
            new_name='status',
        ),
    ]
